# Dependencies

markdown: kramdown
kramdown: 
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "QiYuan's Web"
tagline:          ''
description:      ''
url:              https://qiyuan-zhang.github.io
baseurl:          ''

author:
  name:           'QiYuan Zhang'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
collections:
  figs:
    output:       true
    permalink:    /:collection/:path/
  vlogs:
    output:       true
    permalink:    /:collection/:path/
  Shots:
    output:       true
    permalink:   /:collection/:path/

# Variables
#defaults:
#  -
#    scope:
#      path: ""
#      values:
#        figs_categories: "{{site.figs_categories}}"        # make figs_categories accessable for all pages defined in default.html


  # version:          2.1.0
github:           
  repo:           https://github.com/QiYuan-Zhang/QiYuan-Zhang.github.io

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: qiyuan
